# -*- coding: utf-8 -*-
"""
_image_sitemap.py - write sitemap-images.xml, listing the product photos on
every indexable page.

Why this exists
---------------
A category page's static HTML carries one photo per product: the card image.
Every other photo of that product only appears when JavaScript opens the
product window, so Google Images and Lens may never see it. People do search
by photo here: Search Console shows Lens queries from owners photographing
Sherman pieces ("who is artist", "it says 925"). An image sitemap tells Google
about every photo and which page it belongs to.

What goes in
------------
For each URL in sitemap.xml (English and /he/ alike):
  - every res.cloudinary.com image in the page's markup (outside <script>),
    except the logo/favicon;
  - every photo of every active product whose `pages` in data/products.json
    lists that page (a /he/ page takes its English twin's products).
Each photo is listed once per page, at full size (q_auto,f_auto), the same URL
the product window loads. Order follows sitemap.xml, then first appearance.

Run it after the rest of the generator chain (it reads the finished pages).
  python _image_sitemap.py           write sitemap-images.xml
  python _image_sitemap.py --check   exit 1 if the committed file is stale
"""

import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
BASE = "https://shermanartworks.com"
CDN = "https://res.cloudinary.com/doesupaf9/image/upload/"
OUT = os.path.join(ROOT, "sitemap-images.xml")
# The logo doubles as the favicon; it is not a product photo.
SKIP_IDS = {"WhatsApp_Image_2026-05-23_at_14.51.54_xv8lbd"}

IMG_SRC = re.compile(r'<img\b[^>]*?\bsrc="(https://res\.cloudinary\.com/doesupaf9/image/upload/[^"]+)"', re.I)
SCRIPT = re.compile(r"<script\b.*?</script>", re.S | re.I)


def public_id(url):
    """Last path segment of a Cloudinary delivery URL, without extension."""
    last = url.split("?")[0].rstrip("/").rsplit("/", 1)[-1]
    return re.sub(r"\.(jpe?g|png|webp|gif)$", "", last, flags=re.I)


def full_size(pid):
    return CDN + "q_auto,f_auto/" + pid + ".jpg"


def sitemap_pages():
    xml = io.open(os.path.join(ROOT, "sitemap.xml"), encoding="utf-8").read()
    return re.findall(r"<loc>([^<]+)</loc>", xml)


def local_file(url):
    path = url[len(BASE):].lstrip("/")
    if path == "" or path.endswith("/"):
        path += "index.html"
    return path


def products_by_page():
    data = json.load(io.open(os.path.join(ROOT, "data", "products.json"), encoding="utf-8"))
    items = data if isinstance(data, list) else data["products"]
    by_page = {}
    for p in items:
        if p.get("active") is False:
            continue
        for page in p.get("pages", []):
            by_page.setdefault(page, []).extend(p.get("photos", []))
    return by_page


def build():
    by_page = products_by_page()
    rows = []
    for url in sitemap_pages():
        rel = local_file(url)
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            continue
        markup = SCRIPT.sub("", io.open(path, encoding="utf-8-sig").read())
        ids = [public_id(src) for src in IMG_SRC.findall(markup)]
        en_rel = rel[3:] if rel.startswith("he/") else rel
        ids += by_page.get(en_rel, [])
        seen, photos = set(), []
        for pid in ids:
            if pid and pid not in SKIP_IDS and pid not in seen:
                seen.add(pid)
                photos.append(full_size(pid))
        if photos:
            rows.append((url, photos[:1000]))

    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           "<!-- Generated by _image_sitemap.py from sitemap.xml, the pages and data/products.json. Do not edit by hand. -->",
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
           '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">']
    for url, photos in rows:
        out.append("  <url>")
        out.append("    <loc>%s</loc>" % url)
        for img in photos:
            out.append("    <image:image><image:loc>%s</image:loc></image:image>" % img)
        out.append("  </url>")
    out.append("</urlset>")
    return "\n".join(out) + "\n", rows


def main():
    text, rows = build()
    current = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if "--check" in sys.argv:
        if current != text:
            print("sitemap-images.xml is stale: run python _image_sitemap.py")
            sys.exit(1)
        print("sitemap-images.xml is current")
        return
    if current != text:
        with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    print("wrote sitemap-images.xml: %d pages, %d images" % (len(rows), sum(len(p) for _, p in rows)))


if __name__ == "__main__":
    main()
