# -*- coding: utf-8 -*-
"""
_shofar_guide.py - regenerate the shofar sizing table on shofars.html.

Why this exists
---------------
"What size shofar should I buy" is a high-intent question the site sells the
answer to but never answered: sizes and prices existed only inside product
cards and JSON-LD, so no page could win a table or paragraph snippet for it.

The table is built from data/products.json rather than typed by hand, for the
same reason merchant-feed.xml is: four surfaces already carry these prices and
a hand-maintained fifth would drift the first time a price moved. Rerun this
after any shofar price or size change, exactly as you would _merchant_feed.py.

The table lives on shofars.html only. _shofar_pages.py copies that file to the
three sub-pages, so it strips the guide between the markers below - four pages
answering the same question would compete with each other, and the pillar page
should hold the answer.

Usage:  python _shofar_guide.py [--check]
        --check exits non-zero if the table is stale (for a pre-commit hook).
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
START = "<!-- GUIDE:SIZES:START (generated by _shofar_guide.py - do not edit by hand) -->"
END = "<!-- GUIDE:SIZES:END -->"

# id -> (horn label key, which price column). The four ladders are genuinely
# different: kudu decorated designs start at S, but a personalised kudu is also
# offered in Mini and XS, so those two rows have no decorated price.
LADDERS = {
    "rams": {"decorated": "rams-hoshen-stones", "personalised": "custom-shofar"},
    "kudu": {"decorated": "kudu-hoshen-stones", "personalised": "custom-kudu-shofar"},
}
HORN_ORDER = ["rams", "kudu"]
HORN_T = {"rams": "guide_horn_rams", "kudu": "guide_horn_kudu"}
HORN_EN = {"rams": "Ram's horn", "kudu": "Kudu"}


def load():
    with open(os.path.join(ROOT, "data", "products.json"), "r", encoding="utf-8") as f:
        return {p["id"]: p for p in json.load(f)}


def rows():
    """One row per (horn, size), carrying both price columns where offered."""
    prods = load()
    out = []
    for horn in HORN_ORDER:
        spec = LADDERS[horn]
        dec = {s["label"]: s for s in prods[spec["decorated"]]["sizes"]}
        per = {s["label"]: s for s in prods[spec["personalised"]]["sizes"]}
        # Personalised carries every size the horn is offered in (kudu adds
        # Mini/XS below the decorated range), so it defines the row order.
        for label, s in per.items():
            d = dec.get(label)
            if d and (d["range_cm"], d["range_in"]) != (s["range_cm"], s["range_in"]):
                raise SystemExit(
                    "size %s/%s disagrees between %s and %s - fix products.json"
                    % (horn, label, spec["decorated"], spec["personalised"]))
            out.append({
                "horn": horn,
                "label": label,
                "cm": s["range_cm"],
                "inch": s["range_in"],
                "decorated": d["price_ils"] if d else None,
                "personalised": s["price_ils"],
            })
    return out


def table_html():
    body = []
    prev = None
    for r in rows():
        first = r["horn"] != prev
        prev = r["horn"]
        horn_cell = (
            '        <th scope="row" class="guide-horn" data-t="%s">%s</th>\n'
            % (HORN_T[r["horn"]], HORN_EN[r["horn"]])
            if first else
            '        <th scope="row" class="guide-horn guide-horn-cont"><span class="sr-only" data-t="%s">%s</span></th>\n'
            % (HORN_T[r["horn"]], HORN_EN[r["horn"]])
        )
        dec = "&#8362;%s" % format(r["decorated"], ",") if r["decorated"] else "-"
        body.append(
            '      <tr>\n'
            + horn_cell
            + '        <td>%s</td>\n' % r["label"]
            + '        <td>%s</td>\n' % r["cm"]
            + '        <td>%s</td>\n' % r["inch"]
            + '        <td>%s</td>\n' % dec
            + '        <td>&#8362;%s</td>\n' % format(r["personalised"], ",")
            + '      </tr>'
        )
    return (
        '  <div class="guide-table-wrap">\n'
        '    <table class="guide-table">\n'
        '      <caption class="sr-only" data-t="guide_table_caption">Shofar sizes and prices by horn type</caption>\n'
        '      <thead>\n'
        '      <tr>\n'
        '        <th scope="col" data-t="guide_th_horn">Horn</th>\n'
        '        <th scope="col" data-t="guide_th_size">Size</th>\n'
        '        <th scope="col" data-t="guide_th_cm">Length (cm)</th>\n'
        '        <th scope="col" data-t="guide_th_in">Length (in)</th>\n'
        '        <th scope="col" data-t="guide_th_dec">Decorated</th>\n'
        '        <th scope="col" data-t="guide_th_per">Personalised</th>\n'
        '      </tr>\n'
        '      </thead>\n'
        '      <tbody>\n'
        + "\n".join(body) + "\n"
        '      </tbody>\n'
        '    </table>\n'
        '  </div>'
    )


def main(check=False):
    path = os.path.join(ROOT, "shofars.html")
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    if START not in src or END not in src:
        raise SystemExit("shofars.html is missing the GUIDE:SIZES markers")

    block = START + "\n" + table_html() + "\n  " + END
    out = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, src, flags=re.S)

    n = len(rows())
    if out == src:
        print("sizing table already current (%d rows)" % n)
        return 0
    if check:
        print("STALE: sizing table does not match products.json - run _shofar_guide.py")
        return 1
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(out)
    print("regenerated sizing table (%d rows)" % n)
    print("  next: python _shofar_pages.py  &&  python _he_pages.py")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
